import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import type { FastifyInstance, FastifyReply } from "fastify";

const CONTENT_TYPES: Readonly<Record<string, string>> = Object.freeze({
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".ico": "image/x-icon",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".txt": "text/plain; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
});

function contentType(file: string): string {
  return CONTENT_TYPES[path.extname(file).toLowerCase()] ?? "application/octet-stream";
}

async function sendFile(reply: FastifyReply, file: string): Promise<FastifyReply> {
  const body = await readFile(file);
  const immutable = /[.-][a-zA-Z0-9_-]{8,}\.[^.]+$/.test(path.basename(file));
  return reply
    .header("Content-Type", contentType(file))
    .header("Cache-Control", immutable ? "public, max-age=31536000, immutable" : "no-cache")
    .send(body);
}

async function sendIndex(
  reply: FastifyReply,
  indexFile: string,
  desktopToken?: string,
): Promise<FastifyReply> {
  let html = await readFile(indexFile, "utf8");
  if (desktopToken) {
    // The launch token is a lowercase hex string generated by the native app.
    // Seed the existing browser auth seam before any Vite module executes; every
    // REST/SSE/WebSocket client then uses the same established token plumbing.
    if (!/^[0-9a-f]{64}$/.test(desktopToken)) {
      throw new Error("Desktop token has an invalid shape");
    }
    const bootstrap = `<script>localStorage.setItem("devhub-token","${desktopToken}")</script>`;
    html = html.includes("<head>") ? html.replace("<head>", `<head>${bootstrap}`) : bootstrap + html;
  }
  return reply
    .header("Content-Type", "text/html; charset=utf-8")
    .header("Cache-Control", "no-store")
    .header("X-Frame-Options", "DENY")
    .header("Content-Security-Policy", "frame-ancestors 'none'")
    .send(html);
}

/**
 * Serve the built Vite app from the same localhost origin as the API.
 *
 * The browser build intentionally uses relative `/api` URLs plus same-origin SSE
 * and WebSockets. Vite supplies that proxy in development; a packaged desktop app
 * instead points its WebView at this route so every transport keeps the exact same
 * origin without desktop-only branches in the React application.
 */
export async function registerDesktopWebRoutes(
  app: FastifyInstance,
  webDist: string,
  desktopToken?: string,
): Promise<void> {
  const root = path.resolve(webDist);
  const indexFile = path.join(root, "index.html");
  const info = await stat(indexFile);
  if (!info.isFile()) throw new Error(`Desktop web bundle is missing: ${indexFile}`);

  app.get("/*", async (request, reply) => {
    const rawPath = request.url.split("?", 1)[0] ?? "/";
    if (rawPath === "/api" || rawPath.startsWith("/api/")) {
      return reply.code(404).send({ error: "not found" });
    }

    let decoded: string;
    try {
      decoded = decodeURIComponent(rawPath);
    } catch {
      return reply.code(400).send({ error: "invalid path" });
    }
    if (decoded.includes("\0")) return reply.code(400).send({ error: "invalid path" });

    const relative = decoded.replace(/^\/+/, "");
    const candidate = path.resolve(root, relative || "index.html");
    if (candidate !== root && !candidate.startsWith(`${root}${path.sep}`)) {
      return reply.code(400).send({ error: "invalid path" });
    }

    try {
      if ((await stat(candidate)).isFile()) {
        return candidate === indexFile
          ? await sendIndex(reply, indexFile, desktopToken)
          : await sendFile(reply, candidate);
      }
    } catch {
      // Client-side routes intentionally fall through to index.html.
    }
    if (path.extname(relative) || relative.startsWith("assets/")) {
      return reply.code(404).type("text/plain").send("Not found");
    }
    return sendIndex(reply, indexFile, desktopToken);
  });
}
